# Generated by Django 2.2.16 on 2022-08-19 12:12

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220819_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(choices=[(10, 'Best'), (9, 'Perfect'), (8, 'Excellent'), (7, 'Great'), (6, 'Good'), (5, 'Normal'), (4, 'Bad'), (3, 'Poor'), (2, 'Terrible'), (1, 'Worst')], validators=[django.core.validators.MaxValueValidator(10, 'оценка должна быть между 1 и 10'), django.core.validators.MinValueValidator(1, 'оценка должна быть между 1 и 10')]),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.validators.year_validator], verbose_name='Year'),
        ),
    ]
